apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ping-pong-api-sv.fullname" . }}
  labels:
    app: {{ include "ping-pong-api-sv.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ping-pong-api-sv.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ping-pong-api-sv.name" . }}
    spec:
      imagePullSecrets:
        {{- if .Values.imagePullSecrets }}
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
        {{- end }}
      containers:
        - name: ping-pong-api-sv
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
